name: Run Weather Alerts

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (best effort)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run alert script
      run: python main.py

